name: Deploy Chat Application

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # 每小时的第 0 分钟触发一次

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 安装 hydro
        run: |
          sudo whoami
          sudo curl -O https://hydro.ac/setup.sh
          sudo bash setup.sh
      - name: SU
        run: |
          sudo hydrooj cli user setSuperAdmin 1
          sudo hydrooj cli user setPassword 1 ${{ secrets.password }}
      - name: Install and run Cpolar
        run: |
          wget https://www.cpolar.com/static/downloads/install-release-cpolar.sh
          chmod +x install-release-cpolar.sh
          sudo ./install-release-cpolar.sh
          cpolar authtoken ${{ secrets.CPOLAR_TOKEN }}
          nohup cpolar http -region=cn_top -log=stdout 80 > cpolar_tunnel_log.txt 2>&1 &
      - name: Monitor tunnel log for URL
        run: |
          sleep 30 
          TUNNEL_URL=$(grep -o 'https://[0-9a-z]*\.[0-9a-z]*\.cpolar\.top' cpolar_tunnel_log.txt)
          echo "$TUNNEL_URL" > tunnel_url.txt
          echo "--------------------------------"
          cat tunnel_url.txt
          echo "--------------------------------"
      - name: Update README with Cpolar URL
        run: |
          TUNNEL_URL=$(head -n 1 tunnel_url.txt)

          if grep -q "Application is live at:" README.md; then
            sed -i "s#Application is live at: .*#Application is live at: $TUNNEL_URL#g" README.md
          else
            echo "Application is live at: $TUNNEL_URL" >> README.md
          fi
      - name: Stay
        run: |
          sleep 21000
